server:
  port: 9999

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9096/mem:testdb
    username: sa
    password:
  session:
    store-type: jdbc
  ldap:
    # url below is used by the boot actuator for the ldap server health check indicator
    urls: "ldap://localhost:8389/dc=springframework,dc=org"
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

